### ISSUE TITLE
Open needs escape character (windows)

### ISSUE THREAD

**Issue by Apidcloud** [Interagierende-Systeme/openurl#1]
Good afternoon!

Upon trying to use https://github.com/ericadamski/vscode-carbon_now_sh I've noticed that trying to open an url with multiple get parameters (e.g., https://carbon.now.sh/?bg=rgba(0,0,0,0)&code=Hello) doesn't work under Windows because `&` character isn't escaped (i.e., `^&`).

See https://github.com/ericadamski/vscode-carbon_now_sh/issues/8

A simple `url.href = url.href.replace(/&/g, '^&');` does the trick. Not sure about the other platforms though.

Thanks!

**Comment by HikingDev** [comment]
fixed
